### ISSUE TITLE
epub Reader Pages only 300px tall on some themes

### ISSUE THREAD

**Issue by cmroanirgo** [cmroanirgo/wp-epub-reader#1]
Customer feedback:
"on the page it's on, it only displays 300px tall, unless you put it to fullscreen/lightbox view, in which then it looks/works fine. I'm not sure if it's interacting weird with our theme (Avada) or if it's something else"

**Comment by cmroanirgo** [comment]
A workaround would be to play around with some attributes for the page:
eg.
`[epub-reader src='....' height="100%"]` or `[epub-reader src='....' style="min-height:100%"]`

**Comment by cmroanirgo** [comment]
You need to get Avada to ignore ePub Reader Pages. From this link: https://theme-fusion.com/fb-doc/technical/fusion-builder-custom-post-types/

### How To Enable/Disable Fusion Builder On Custom Post Types

1. Navigate to the *Fusion Builder > Settings* tab on your WP admin sidebar.
2. On the Settings page, you’ll find the ‘Post Types’ section.
3. Check the corresponding post type checkbox to enable the Fusion Builder on it. You can also choose to uncheck it to disable the Fusion Builder instead.

**Comment by davidpwhelan** [comment]
Thanks for this.  I had the same problem with the Keratin theme, and so didn't have any obvious way to fix it in the manner you described with Fusion Builder.  The shortcode ignored my height= parameter entirely.  But adding 'style="min-height: 800px;" inside the short code worked great; width was already 100% of content.  

Thanks again; it's a really excellent plugin.
