### ISSUE TITLE
Epub not displaying

### ISSUE THREAD

**Issue by agxer** [cmroanirgo/wp-epub-reader#10]
Hi, I just get a blank white screen when I add the shortcode to an epub reader page.

If i insert the same shortcode in any other page/post i get the reader frame but just the spinner keeps going. 

My epub file is stored in a sub-directory of the root folder and the full path to the epub file is in the shortcode. 

Is there something I am missing?

**Comment by cmroanirgo** [comment]
Thanks for the feedback, but this was just a weekend project and unfortunately, I don't have time to maintain nor provide any form of support it. You are welcome to fork it if you like.
