### ISSUE TITLE
something wrong in epub-reader-frame.php 

### ISSUE THREAD

**Issue by fcki1984** [cmroanirgo/wp-epub-reader#8]
on line 40  ` :$book_zip = strstr($book_path, '.epub') || htmlspecialchars($_GET["zip"])=='1';`
the post shows a bug :Undefined index: zip in/*/wp-content/plugins/epub-reader/public/views/epub-reader-frame.php on line 40. 
so I deleted the second half of the line:  `|| htmlspecialchars($_GET["zip"])=='1' ` , and the wrong is fixed.

**Comment by cmroanirgo** [comment]
Thanks for the feedback, but this was just a weekend project and unfortunately, I don't have time to maintain it. You are welcome to fork it if you like.
